### ISSUE TITLE
[WEB3系列教程之进阶篇---教程索引]里面的链接失效了

### ISSUE THREAD

**Issue by huaigu** [hicoldcat/hicoldcat.com#1]
[本地区块链测试](https://hicoldcat.com/posts/web3/junior-tarck-5/)

比如上面这个链接

**Comment by hicoldcat** [comment]
> [本地区块链测试](https://hicoldcat.com/posts/web3/junior-tarck-5/)
> 
> 比如上面这个链接

字母拼错了，已更正，非常感谢😊
